## DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/trivia_game
spring.datasource.username=trivia_user
spring.datasource.password=tr1v1a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## THYMELEAF CONFIGURATION
spring.thymeleaf.prefix=classpath:/html/

## JWT CONFIGURATION
jwt.token.ttl.seconds=500
jwt.secret.password=my-secret-password